#ifndef includes_h
#define includes_h
#include <SFML/Audio.hpp>
#include <SFML/Graphics.hpp>
#include "sqlite3.h"
#include <algorithm>
#include <ctime>
#include <cstring>
#include <functional>
#include "dino.h"
#include "Textbox.h"
#include <sstream>
#include <cstdio>
#include <cassert>
#include <string>
#include <list>
#include <memory>
#include <iostream>
#include <vector>
#include <map>
#include <chrono>
#include <thread>
#include "AssetManager.h"
#endif